class RadioStation {
  final String state;
  final String city;
  final String callsign;
  final String url;
  const RadioStation(this.state, this.city, this.callsign, this.url);
  String get label => '$city, $state';
}

const radioStations = <RadioStation>[
  RadioStation('AL', 'Mobile', 'KEC61', 'https://radio.weatherusa.net/NWR/KEC61_2.mp3'),
  RadioStation('AZ', 'Globe', 'WWG42', 'https://wxradio.org/AZ-Globe-WWG42'),
  RadioStation('AZ', 'Mammoth', 'WXL30', 'https://radio.weatherusa.net/NWR/WXL30.mp3'),
  RadioStation('AZ', 'Payson/Gila County', 'WWG41', 'https://wxradio.org/AZ-PaysonGilaCountyN-WWG41'),
  RadioStation('AZ', 'Phoenix', 'KEC94', 'https://wxradio.org/AZ-Phoenix-KEC94'),
  RadioStation('AZ', 'Yuma', 'WXL87', 'https://radio.weatherusa.net/NWR/WXL87.mp3'),
  RadioStation('CA', 'Apple Valley', 'WXM66', 'https://radio.weatherusa.net/NWR/WXM66.mp3'),
  RadioStation('CA', 'Coachella', 'KIG78', 'https://radio.weatherusa.net/NWR/KIG78_2.mp3'),
  RadioStation('CA', 'Fresno', 'KIH62', 'https://radio.weatherusa.net/NWR/KIH62_2.mp3'),
  RadioStation('CA', 'Monterey Marine', 'WWF64', 'https://wxradio.org/CA-MontereyMarine-WWF64'),
  RadioStation('CA', 'San Diego Marine', 'WNG637', 'https://radio.weatherusa.net/NWR/WNG637_2.mp3'),
  RadioStation('CA', 'San Diego', 'KEC62', 'https://radio.weatherusa.net/NWR/KEC62_2.mp3'),
  RadioStation('CA', 'San Francisco Bay', 'KEC49', 'https://wxradio.org/CA-Monterey-KEC49'),
  RadioStation('CO', 'Durango', 'KWN54', 'https://radio.weatherusa.net/NWR/KWN54.mp3'),
  RadioStation('CT', 'Hartford', 'WXJ41', 'https://radio.weatherusa.net/NWR/WXJ41_2.mp3'),
  RadioStation('CT', 'Meriden', 'WXJ42', 'https://wxradio.org/CT-Meriden-WXJ42'),
  RadioStation('FL', 'Cape Coral', 'WXK83', 'https://wxradio.org/FL-FortMyers-WXK83'),
  RadioStation('FL', 'Orlando', 'KIH63', 'https://wxradio.org/FL-Orlando-KIH63'),
  RadioStation('FL', 'Palatka', 'WNG522', 'https://wxradio.org/FL-Palatka-WNG522'),
  RadioStation('FL', 'Sumterville', 'KPS505', 'https://wxradio.org/FL-Sumterville-KPS505'),
  RadioStation('FL', 'Tallahassee', 'KIH24', 'https://wxradio.org/FL-Tallahassee-KIH24'),
  RadioStation('FL', 'Tampa Bay', 'KHB32', 'https://wxradio.org/FL-TampaBay-KHB32'),
  RadioStation('GA', 'Athens', 'WXK56', 'https://wxradio.org/GA-Athens-WXK56'),
  RadioStation('GA', 'Atlanta', 'KEC80', 'https://wxradio.org/GA-Atlanta-KEC80'),
  RadioStation('GA', 'Buchanan', 'WWH23', 'https://wxradio.org/GA-Buchanan-WWH23'),
  RadioStation('GA', 'Columbus', 'WXM32', 'https://radio.weatherusa.net/NWR/WXM32.mp3'),
  RadioStation('HI', 'Maui', 'WWG75', 'https://wxradio.org/HI-Maui-WWG75'),
  RadioStation('IA', 'Des Moines', 'WXL57', 'https://radio.weatherusa.net/NWR/WXL57.mp3'),
  RadioStation('IA', 'Milford', 'KZZ80', 'https://wxradio.org/IA-Milford-KZZ80'),
  RadioStation('IA', 'Sioux City', 'WXL62', 'https://wxradio.org/IA-Sioux_City-WXL62'),
  RadioStation('IA', 'St Ansgar', 'KXI68', 'https://wxradio.org/IA-StAnsgar-KXI68'),
  RadioStation('IL', 'Champaign', 'WXJ76', 'https://wxradio.org/IL-Champaign-WXJ76'),
  RadioStation('IL', 'Crystal Lake', 'KXI41', 'https://wxradio.org/IL-CrystalLake-KXI41'),
  RadioStation('IL', 'Dixon', 'KZZ55', 'https://radio.weatherusa.net/NWR/KZZ55.mp3'),
  RadioStation('IL', 'Galesburg', 'KZZ66', 'https://wxradio.org/IL-Galesburg-KZZ66'),
  RadioStation('IL', 'Kankakee', 'KZZ58', 'https://wxradio.org/IL-Kankakee-KZZ58'),
  RadioStation('IL', 'Marion', 'WXM49', 'https://wxradio.org/IL-Marion-WXM49-ALT1'),
  RadioStation('IL', 'Peoria', 'WXJ71', 'https://wxradio.org/IL-Peoria-WXJ71'),
  RadioStation('IL', 'Plano', 'KXI58', 'https://radio.weatherusa.net/NWR/KXI58.mp3'),
  RadioStation('IL', 'Quad Cities', 'WXJ73', 'https://wxradio.org/IL-QuadCities-WXJ73'),
  RadioStation('IL', 'Springfield', 'WXJ75', 'https://radio.weatherusa.net/NWR/WXJ75.mp3'),
  RadioStation('IN', 'Indianapolis', 'KEC74', 'https://wxradio.org/IN-Indianapolis-KEC74'),
  RadioStation('IN', 'South Bend', 'WXJ57', 'https://wxradio.org/IN-SouthBend-WXJ57'),
  RadioStation('KS', 'Topeka', 'WXK91', 'https://wxradio.org/KS-Topeka-WXK91-alt1'),
  RadioStation('KY', 'Frankfort', 'WZ2523', 'https://wxradio.org/KY-Frankfort-WZ2523'),
  RadioStation('KY', 'Owenton', 'KZZ48', 'https://wxradio.org/KY-Owenton-KZZ48'),
  RadioStation('LA', 'Baton Rouge', 'KHB46', 'https://radio.weatherusa.net/NWR/KHB46.mp3'),
  RadioStation('LA', 'Lafayette', 'WXK80', 'https://radio.weatherusa.net/NWR/WXK80.mp3'),
  RadioStation('LA', 'Monroe', 'WXJ96', 'https://radio.weatherusa.net/NWR/WXJ96_2.mp3'),
  RadioStation('LA', 'Shreveport', 'WXJ97', 'https://wxradio.org/LA-Shreveport-WXJ97'),
  RadioStation('MA', 'Boston', 'KHB35', 'https://radio.weatherusa.net/NWR/KHB35_3.mp3'),
  RadioStation('MA', 'Bourne', 'KEC73', 'https://wxradio.org/MA-Bourne/Hyannis-KEC73'),
  RadioStation('MA', 'Gloucester', 'WNG574', 'https://radio.weatherusa.net/NWR/WNG574.mp3'),
  RadioStation('MA', 'Worcester', 'WXL93', 'https://wxradio.org/MA-Worcester-WXL93'),
  RadioStation('MD', 'Baltimore', 'KEC83', 'https://radio.weatherusa.net/NWR/KEC83_3.mp3'),
  RadioStation('MD', 'Hagerstown', 'WXM42', 'https://noaa-manassas-radio.from-va.com/Hagerstown.mp3'),
  RadioStation('ME', 'Dresden', 'WSM60', 'https://wxradio.org/ME-Dresden-WSM60'),
  RadioStation('ME', 'Falmouth/Portland', 'KDO95', 'https://radio.weatherusa.net/NWR/KDO95.mp3'),
  RadioStation('MI', 'Detroit', 'KEC63', 'https://radio.weatherusa.net/NWR/KEC63.mp3'),
  RadioStation('MI', 'Flint', 'KIH29', 'https://wxradio.org/MI-Clio-KIH29'),
  RadioStation('MI', 'Gaylord', 'WWF70', 'https://wxradio.org/MI-Gaylord-WWF70'),
  RadioStation('MI', 'Hesperia', 'WWF36', 'https://wxradio.org/MI-Hesperia-WWF36'),
  RadioStation('MI', 'Kalamazoo', 'WWF34', 'https://icecast.wxstream.org/NWR/WWF34'),
  RadioStation('MI', 'Mount Pleasant', 'KZZ33', 'https://wxradio.org/MI-MountPleasant-KZZ33'),
  RadioStation('MI', 'Onondaga', 'WXK81', 'https://icecast.wxstream.org/NWR/WXK81'),
  RadioStation('MI', 'West Branch', 'KXI33', 'https://wxradio.org/MI-WestBranch-KXI33'),
  RadioStation('MI', 'West Olive', 'WXN99', 'https://radio.weatherusa.net/NWR/WXN99.mp3'),
  RadioStation('MI', 'Wolf Lake', 'WNG672', 'https://herseynoaaradio.freeddns.org/MI-WolfLake-WNG672-alt1'),
  RadioStation('MN', 'Bemidji', 'WXM99', 'https://wxr.bemidjiwx.org/WXM99'),
  RadioStation('MN', 'Clearwater', 'WNG676', 'https://radio.weatherusa.net/NWR/WNG676.mp3'),
  RadioStation('MN', 'La Crescent', 'WXJ86', 'https://wxradio.org/MN-LaCrescent-WXJ86'),
  RadioStation('MN', 'Minneapolis', 'KEC65', 'https://radio.weatherusa.net/NWR/KEC65.mp3'),
  RadioStation('MN', 'Park Rapids', 'WWG98', 'https://wxr.bemidjiwx.org/WWG98'),
  RadioStation('MN', 'Rochester', 'WXK41', 'https://stream.zeno.fm/ekqs8ehdknivv'),
  RadioStation('MO', 'Kansas City', 'KID77', 'https://radio.weatherusa.net/NWR/KID77_3.mp3'),
  RadioStation('MO', 'Springfield', 'WXL46', 'https://wxradio.org/MO-Springfield-WXL46'),
  RadioStation('MO', 'St. Louis', 'KDO89', 'https://wxradio.org/MO-StLouis-KDO89'),
  RadioStation('MS', 'Tupelo', 'KIH53', 'https://radio.weatherusa.net/NWR/KIH53.mp3'),
  RadioStation('NC', 'Charlotte', 'WXL70', 'https://wxradio.org/NC-Charlotte-WXL70'),
  RadioStation('NC', 'Wilmington', 'KHB31', 'https://radio.weatherusa.net/NWR/KHB31_3.mp3'),
  RadioStation('ND', 'Bismarck', 'WXL78', 'https://wxradio.org/ND-Bismarck-WXL78'),
  RadioStation('NE', 'Beatrice', 'KZZ69', 'https://radio.weatherusa.net/NWR/KZZ69.mp3'),
  RadioStation('NE', 'Grand Island', 'WXL74', 'https://wxradio.org/NE-GrandIsland-WXL74'),
  RadioStation('NE', 'Lincoln', 'WXM20', 'https://wxradio.org/NE-Lincoln-WXM20-alt1'),
  RadioStation('NE', 'Omaha', 'KIH61', 'https://radio.weatherusa.net/NWR/KIH61.mp3'),
  RadioStation('NE', 'Scottsbluff', 'WXL67', 'https://wxradio.org/NE-Scottsbluff-WXL67'),
  RadioStation('NM', 'Farmington', 'WXJ37', 'https://radio.weatherusa.net/NWR/WXJ37.mp3'),
  RadioStation('NV', 'Fernley', 'WWG20', 'https://radio.weatherusa.net/NWR/WWG20.mp3'),
  RadioStation('NV', 'Reno', 'WXK58', 'https://radio.weatherusa.net/NWR/WXK58.mp3'),
  RadioStation('NY', 'Albany', 'WXL34', 'https://wxradio.org/NY-Albany-WXL34'),
  RadioStation('NY', 'Buffalo', 'KEB98', 'https://radio.weatherusa.net/NWR/KEB98.mp3'),
  RadioStation('NY', 'Highland', 'WXL37', 'https://radio.weatherusa.net/NWR/WXL37.mp3'),
  RadioStation('NY', 'Lyons', 'WZ2536', 'https://wxradio.org/NY-Lyons-WZ2536'),
  RadioStation('NY', 'Middleville', 'WXM45', 'https://radio.weatherusa.net/NWR/WXM45.mp3'),
  RadioStation('NY', 'New York City', 'KWO35', 'https://www.saucci.net:8443/audio3.ogg'),
  RadioStation('NY', 'Rochester', 'KHA53', 'https://wxradio.org/NY-Rochester-KHA53'),
  RadioStation('NY', 'Syracuse', 'WXL31', 'https://wxradio.org/NY-Syracuse-WXL31'),
  RadioStation('OH', 'Akron', 'KDO94', 'https://radio.weatherusa.net/NWR/KDO94.mp3'),
  RadioStation('OH', 'Columbus', 'KIG86', 'https://radio.weatherusa.net/NWR/KIG86.mp3'),
  RadioStation('OH', 'Grafton', 'WNG698', 'https://wxradio.org/OH-Grafton-WNG698'),
  RadioStation('OH', 'Mansfield', 'WWG57', 'https://wxradio.org/OH-Mansfield-WWG57'),
  RadioStation('OH', 'Toledo', 'WXL51', 'https://wxradio.org/OH-Toledo-WXL51'),
  RadioStation('OK', 'Lawton', 'WXK86', 'https://radio.weatherusa.net/NWR/WXK86.mp3'),
  RadioStation('OK', 'Oklahoma City', 'WXK85', 'https://radio.weatherusa.net/NWR/WXK85.mp3'),
  RadioStation('OK', 'Stillwater', 'WNG654', 'https://wxradio.org/OK-Stillwater-WNG654'),
  RadioStation('OK', 'Tulsa', 'KIH27', 'https://wxradio.org/OK-Tulsa-KIH27'),
  RadioStation('PA', 'Harrisburg', 'WXL40', 'https://wxradio.org/PA-Harrisburg-WXL40'),
  RadioStation('PA', 'Hibernia Park', 'WNG704', 'https://wxradio.org/PA-HiberniaPark-WNG704'),
  RadioStation('PA', 'Philadelphia', 'KIH28', 'https://radio.weatherusa.net/NWR/KIH28_3.mp3'),
  RadioStation('PA', 'Pittsburgh', 'KIH35', 'https://radio.weatherusa.net/NWR/KIH35.mp3'),
  RadioStation('PA', 'Wilkes-Barre', 'WXL43', 'https://wxradio.org/PA-WilkesBarre-WXL43'),
  RadioStation('SC', 'Greer', 'WXJ21', 'https://wxradio.org/SC-Greenville-WXJ21'),
  RadioStation('SC', 'Jasper County', 'KEC85', 'https://wxradio.org/SC-Savannah-KEC85'),
  RadioStation('SC', 'Rock Hill', 'KHC27', 'https://wxradio.org/SC-RockHill-KHC27'),
  RadioStation('TN', 'Bristol', 'WXK47', 'https://radio.weatherusa.net/NWR/WXK47_2.mp3'),
  RadioStation('TN', 'Memphis', 'WXK49', 'https://usa10.fastcast4u.com:3210/1'),
  RadioStation('TN', 'Shelbyville', 'WXK63', 'https://radio.weatherusa.net/NWR/WXK63.mp3'),
  RadioStation('TN', 'White House', 'KIG79', 'https://radio.weatherusa.net/NWR/KIG79_2.mp3'),
  RadioStation('TX', 'Amarillo', 'WXK38', 'https://radio.weatherusa.net/NWR/WXK38_2.mp3'),
  RadioStation('TX', 'Austin', 'WXK27', 'https://wxradio.org/TX-Austin-WXK27'),
  RadioStation('TX', 'College Station', 'WXK30', 'https://radio.weatherusa.net/NWR/WXK30.mp3'),
  RadioStation('TX', 'Corpus Christi', 'KHB41', 'https://radio.weatherusa.net/NWR/KHB41_2.mp3'),
  RadioStation('TX', 'Corsicana', 'KXI87', 'https://radio.weatherusa.net/NWR/KXI87.mp3'),
  RadioStation('TX', 'Dallas', 'KEC56', 'https://radio.weatherusa.net/NWR/KEC56_3.mp3'),
  RadioStation('TX', 'Fort Worth', 'KEC55', 'https://radio.weatherusa.net/NWR/KEC55_2.mp3'),
  RadioStation('TX', 'Galveston', 'KHB40', 'https://radio.weatherusa.net/NWR/KHB40.mp3'),
  RadioStation('TX', 'Houston/Tomball', 'KGG68', 'https://radio.weatherusa.net/NWR/KGG68.mp3'),
  RadioStation('TX', 'Lufkin', 'WXK23', 'https://radio.weatherusa.net/NWR/WXK23.mp3'),
  RadioStation('TX', 'Odessa', 'WXK32', 'https://radio.weatherusa.net/NWR/WXK32.mp3'),
  RadioStation('TX', 'Palestine', 'KWN34', 'https://radio.weatherusa.net/NWR/KWN34.mp3'),
  RadioStation('TX', 'San Angelo', 'WXK33', 'https://radio.weatherusa.net/NWR/WXK33_2.ogg'),
  RadioStation('TX', 'Tyler', 'WXK36', 'https://radio.weatherusa.net/NWR/WXK36_2.mp3'),
  RadioStation('TX', 'Waco', 'WXK35', 'https://radio.weatherusa.net/NWR/EW6308.mp3'),
  RadioStation('VA', 'Emporia', 'WWG33', 'https://radio.weatherusa.net/NWR/AKQ.mp3'),
  RadioStation('VA', 'Manassas', 'KHB36', 'https://stream.mikev.com/khb36.mp3'),
  RadioStation('VA', 'Roanoke', 'WXL60', 'https://radio.weatherusa.net/NWR/WXL60.mp3'),
  RadioStation('VA', 'Virginia Beach', 'KHB37', 'https://radio.weatherusa.net/NWR/KHB37_3.mp3'),
  RadioStation('WA', 'Davis Peak', 'WNG604', 'https://radio.weatherusa.net/NWR/WNG604_2.mp3'),
  RadioStation('WA', 'Puget Sound Marine', 'WWG24', 'https://wxradio.bobc.io/stream/WWG24'),
  RadioStation('WA', 'Richland', 'WWF56', 'https://radio.weatherusa.net/NWR/WWF56_2.mp3'),
  RadioStation('WA', 'Seattle', 'KHB60', 'https://wxradio.bobc.io/stream/KHB60'),
  RadioStation('WI', 'Ashland', 'KZZ78', 'https://wxradio.org/WI-Ashland-KZZ78'),
  RadioStation('WI', 'Green Bay', 'KIG65', 'https://wxradio.org/WI-GreenBay-KIG65'),
  RadioStation('WI', 'Menomonie', 'WXJ88', 'https://radio.weatherusa.net/NWR/WXJ88.mp3'),
  RadioStation('WI', 'Wausaukee', 'WNG553', 'https://wxradio.org/WI-Wausaukee-WNG553'),
  RadioStation('WI', 'Winona', 'KGG95', 'https://radio.weatherusa.net/NWR/KGG95.mp3'),
  RadioStation('WI', 'Withee', 'KZZ77', 'https://wxradio.org/WI-Withee-KZZ77'),
  RadioStation('WV', 'Parkersburg', 'WXM70', 'https://radio.weatherusa.net/NWR/KWN75.mp3'),
  RadioStation('WY', 'Lander', 'WXM61', 'https://radio.weatherusa.net/NWR/WXM61.mp3'),
];
